#!/bin/bash
water_dec=$(echo $WATER | tr 'water' '01234')
stir_dec=$(echo $STIR | tr 'stir' '01234')
result_dec=$((water_dec + stir_dec))
result_bestchol=$(echo $result_dec | tr '0123456789' 's0g7q5r3m9f')
echo $result_bestchol
