#!/bin/bash
result=$(echo "$WATER" | tr 'water' '01234' | tr -d '\n' | xargs printf '%d\n' | awk '{a=$1; getline < "/dev/stdin"; print a+$1}' FS= "$(echo "$STIR" | tr 'stir' '01234' | tr -d '\n' | xargs printf '%d\n' | tr '\n' ' ')" | (printf 'obase=10\n'; cat) | tr -d '\n' | bc)
echo "$result" | tr '0123456789' 's0g7q5r3m9f'
